# Generated by Django 5.2.12 on 2026-03-09 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Номер заказа')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('cdek_order_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID заказа в СДЭК')),
                ('cdek_track_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Трек-номер СДЭК')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('accepted', 'Принят СДЭК'), ('pickup', 'Готов к выдаче'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('cdek_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус от СДЭК')),
                ('cdek_status_code', models.IntegerField(blank=True, null=True, verbose_name='Код статуса СДЭК')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_cdek_check', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка СДЭК')),
                ('items', models.JSONField(default=dict, verbose_name='Товары')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Код статуса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('date', models.DateTimeField(verbose_name='Дата события')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracking.order')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-date'],
            },
        ),
    ]
